remote: true

experienceLevel:
  internship: true
  entry: true
  associate: false
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: true
  temporary: false
  internship: true
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: true
  24 hours: true

positions:
  - Software engineer
  - Frontend developer
  - Fullstack developer
  - Backend developer
  - Software Engineer Intern
  - Intern Web Developer
  - Intern Frontend Developer
  - Intern Backend Developer
  

locations:
  - United States
  - Chicago
  - New York
  - Chicago
  - San Francisco

apply_once_at_company: false

distance: 0

company_blacklist:

title_blacklist:

job_applicants_threshold:
  min_applicants: 0

llm_model_type: openai
llm_model: 'gpt-4o'
llm_api_url: https://api.pawan.krd/cosmosrp/v1'
